services:
  - type: web
    name: get-github-jwt
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
